- name: configuring the cart service
  hosts: cart
  become: yes
  tasks:
  - name: setting up the nodejs repo
    ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

  - name: Install NodeJS
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: Add application User if user does not exist 
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: print the output 
    ansible.builtin.debug:
      msg: "{{output.rc}}"

  - name: create the user
    ansible.builtin.user:
      name: "roboshop" 
    when: output.rc != 0 

  - name: check if the /app directory exists , if not create one
    ansible.builtin.stat:
      path: /app
    register: output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{output}}"

  - name: craete a directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: output.stat.exists == false 

  - name: download the artifact code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: unzip the artifact code in /app directory
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: Install the dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app
  - name: setting up the systemd service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: deamon reload
    ansible.builtin.systemd:
      daemon_reload: true

  - name: start and enable the Service
    ansible.builtin.service:
      name: cart
      enabled: yes
      state: started         


