- name: Configuring the Catalouge service
  hosts: catalouge
  become: yes
  tasks:
  - name: Setup NodeJS repos
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: Install NodeJS  
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: check if the user "roboshop" exists or not , if not create a user
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name:  print the output
    ansible.builtin.debug:
      msg: "output is : {{output.rc}}"

  - name:  check the exit status , if not equals to 0 , create a user
    ansible.builtin.user:
      name: "roboshop" 
    when: output.rc !=0

  - name: check if the /app directory exists, if not create one
    ansible.builtin.stat:
      path: /app
    register: output

  - name: print the exit status
    ansible.builtin.debug:
      msg: "{{output}}"
   
  - name: Create a directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: output.stat.exists == false

  - name: Download the application code to created app directory
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: Extract the Catalouge artifact in /app
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes # means catalouge.zip already available in catalouge server otherise it checks dor the catalouge.zip in the ansible server

  - name: Install the application dependencies
    ansible.builtin.command: npm install
    #we have to change the directory to /app
    args:
      chdir: /app

  - name: Setup SystemD Catalogue Service
    ansible.builtin.copy:
      src: catalouge.service
      dest: /etc/systemd/system/catalouge.service

  - name: demon-reload the service
    ansible.builtin.systemd:
      daemon_reload: true

  - name: start and enable the Service
    ansible.builtin.service:
      name: catalouge
      enabled: yes 
      state: started

  - name: to load the schema , set up mongodb repo and install mongodb client
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb client'
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed 

  - name: load the schema
    ansible.builtin.command: mongo --host mongodb.devopsvani.online < /app/schema/catalogue.js               