- name: configure user service
  hosts: user
  become: yes
  tasks:
  - name: Setup NodeJS repos
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: Install NodeJS
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: Add application User if user does not exist 
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "output is {{output.rc}}" 

  - name: create the user if not exist
    ansible.builtin.user:
      name: "roboshop"   
    when: output.rc !=0 

  - name: check if the /app directory exist , if not create one
    ansible.builtin.stat:
      path: /app
    register: output  

  - name: print the output 
    ansible.builtin.debug:
      msg: "{{output}}"

  - name: create the /app directory 
    ansible.builtin.file:
      path: /app
      state: directory
    when: output.stat.exists == fasle           



